name: Update versions

on:
  schedule:
    - cron: '0 0 * * *'  # run this job every day at midnight

jobs:
  update-versions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yolk3k

    - name: Get latest versions from PyPI
      run: |
        echo "COFI_VERSION=$(yolk -M cofi -f version)" > versions.txt
        echo "ESPRESSO_VERSION=$(yolk -M geo-espresso -f version)" >> versions.txt
        echo "COFI_EXAMPLES_VERSION=$(curl -s 'https://api.github.com/repos/inlab-geo/cofi-examples/commits/main' | jq -r '.sha')" >> versions.txt

    - name: Commit and push if it changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m 'Update versions' && git push)
