ARG COFI_VERSION="latest"
ARG ESPRESSO_VERSION="latest"
ARG COFI_EXAMPLES_VERSION="latest"

FROM quay.io/jupyter/scipy-notebook as base

# Add RUN statements to install packages as the $NB_USER defined in the base images.

# Add a "USER root" statement followed by RUN statements to install system packages using apt-get,
# change file permissions, etc.

# If you do switch to root, always be sure to add a "USER $NB_USER" command at the end of the
# file to ensure the image runs as a unprivileged user by default.

FROM base AS cofi
ARG COFI_VERSION
RUN mamba install --quiet --yes --name base "scipy<1.13.0" && \
    # TODO remove the above after seislib releases new version
    if [ "$COFI_VERSION" = "latest" ] ; \
        then python -m pip install --no-cache-dir -U cofi ; \
        else python -m pip install --no-cache-dir -U cofi==$COFI_VERSION ; \
    fi

FROM base AS espresso
ARG ESPRESSO_VERSION
USER root
RUN apt-get update && apt-get install -y g++ gfortran
USER $NB_USER
RUN mamba install --quiet --yes --name base cython cartopy && \
    if [ "$ESPRESSO_VERSION" = "latest" ] ; \
        then python -m pip install --no-cache-dir -U geo-espresso ; \
        else python -m pip install --no-cache-dir -U geo-espresso==$ESPRESSO_VERSION ; \
    fi

FROM cofi AS cofi_n_espresso
ARG ESPRESSO_VERSION
USER root
RUN apt-get update && apt-get install -y g++ gfortran
USER $NB_USER
RUN mamba install --quiet --yes --name base cython cartopy && \
    if [ "$ESPRESSO_VERSION" = "latest" ] ; \
        then python -m pip install --no-cache-dir -U geo-espresso ; \
        else python -m pip install --no-cache-dir -U geo-espresso==$ESPRESSO_VERSION ; \
    fi

FROM cofi_n_espresso AS inlab
ARG COFI_EXAMPLES_VERSION
RUN git clone https://github.com/inlab-geo/cofi-examples.git && \
    if [ "$COFI_EXAMPLES_VERSION" != "latest" ] ; \
        then git -C cofi-examples checkout $COFI_EXAMPLES_VERSION ; \
    fi && \
    python -m pip install --no-cache-dir -r cofi-examples/envs/requirements.txt
