# syntax=docker/dockerfile:1

# Add RUN statements to install packages as the $NB_USER defined in the base images.

# Add a "USER root" statement followed by RUN statements to install system packages using apt-get,
# change file permissions, etc.

# If you do switch to root, always be sure to add a "USER $NB_USER" command at the end of the
# file to ensure the image runs as a unprivileged user by default.

FROM jupyter/minimal-notebook:python-3.9.13 as base

FROM base AS cofi
RUN python -m pip install --no-cache-dir -U cofi

FROM base AS espresso
RUN python -m pip install --no-cache-dir -U geo-espresso

FROM cofi AS cofi_n_espresso
RUN python -m pip install --no-cache-dir -U geo-espresso

FROM cofi_n_espresso AS inlab
RUN mamba install --quiet --yes --name base \
        --channel gimli --channel conda-forge \
        simpeg pygimli=1.3.0 \
    && git clone https://github.com/inlab-geo/cofi-examples.git
